### ISSUE TITLE
'protobuf/text_format.h' file not found when building "Quickstart with CMake"

### ISSUE THREAD

**Issue by d2weber** [google/fuzztest#1192]
I followed the steps in [Quickstart with CMake](https://github.com/google/fuzztest/blob/main/doc/quickstart-cmake.md) and ran into a compilation Error:
```
In file path/to/first_fuzz_project/fuzztest/./fuzztest/internal/table_of_recent_compares.h:31:
path/to/first_fuzz_project/fuzztest/./fuzztest/internal/type_support.h:42:10: fatal error: 'google/protobuf/text_format.h' file not found
#include "google/protobuf/text_format.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I ran git bisect to find a commit that compiles:
```
git bisect good 6a370aed314173f472b265c8196bd4810846c831
# first bad commit: [ed6f817771702bf7823b73498d0e1914475f2313] Properly convert proto to text
```

I use Ubuntu 22.04 with Clang 14.0.0

**Comment by pyu1538** [comment]
I met the same error. It depends on the system protobuf library, I resolved it by the following command:
sudo apt install -y protobuf-compiler libprotobuf-dev

**Comment by fniksic** [comment]
Should be fixed by #1219.
